

## Config settings file for WinDusky appliation .. repository: https://github.com/yakrider/WinDusky
# This file uses the toml format: https://toml.io
#
# The application will look for this file (WinDusky.conf.toml) in the same directory from which it is running (if the location is writeable)
# If that location is not writeable, the config file will pick  ~/AppData/Local/WinDusky/ as conf file location
# Upon startup, if the conf file is not present in the location selected as above, a default conf file will be created in that location
# Configurations modified at run time will be written back to this file
# Most changes to this file (unless specified in the config) will be picked up by the application upon restart




# WinDusky conf version string .. this is used to check compatibility and print warnings/errors
# Upon upgrading the application, and updating any user configs here as desired, can update this version string to remove warning printouts
dusky_conf_version = 0.18



# Enable logging for debugging or reporting errors .. default is false
# When enabled, the log files with names like "WinDusky_log.<date>.log" will be generated in the same location as the active config file
# Note: Enabling logging is only picked up upon restarting the application
logging_enabled = true

# Level of logging (if enabled) .. default is "INFO" .. options are "DEBUG", "INFO", "WARN", "ERROR"
logging_level = "INFO"




# Hotkey to toggle WinDusky on currectly active window, specified as a string ..
# Hotkey specification are in keys.rs file in this repo .. they are case-insensitive and summarized below :
#   Alt, Shift, Ctrl, Win, A-Z, 0-9, F1-F24, Comma, Period, Plus, Minus, SemiColon, Slash, Backslash etc,
#   Up, Down, Left, Right, Home, End, PgUp, PgDown,
#   Space, Enter, Backspace, Delete, Insert, Tab, Escape
#
# Note: Updates to this config are ONLY picked up upon restarting (not just reloading) the application
# The default is "Alt+Win+I" .. I for 'invert' .. specified as { key = "I", modifiers = ["Alt", "Win"] }
hotkey__dusky_toggle = { key = "I", modifiers = ["Alt", "Win"] }


# Hotkey to toggle dusky color effect mode to 'FullScreen' rather than per window
# The default is "Alt+Win+Shift+I" .. specified as { key = "I", modifiers = ["Alt", "Win", "Shift"] }
hotkey__fullscreeen_toggle = { key = "I", modifiers = ["Alt", "Win", "Shift"] }


# Hotkeys to cycle through (next and previous) color-effects in the color-effects list
# The defaults are Alt+Win+Period for Next, and Alt+Win+Comma for Previous effect
hotkey__next_effect = { key = "Period", modifiers = ["Alt", "Win"] }
hotkey__prev_effect = { key = "Comma",  modifiers = ["Alt", "Win"] }


# Hotkey to clear all user toggling performed on overlays, including overrides to any auto-applied overlays
# Clearing these means auto-overlay rules can reapply to windows when they come to foreground next
hotkey__clear_overrides = { key = "Insert", modifiers = ["Alt", "Win"] }

# Hotkey to clear all active overlays (will also clear all user overrides)
hotkey__clear_overlays = { key = "Delete", modifiers = ["Alt", "Win"] }






# --- Auto Overlay Configuration ---

# Note: The 'effect' field for rules defined here can refer to names defined in the [[effects]] tables.
# Use "default" to apply the effect specified in 'effects_default'
# This default also gets used if nothing is specified


# Average luminance threshold (darkest 0.0 and brightest 1.0) above which a window should automatically have the default overlay applied
# For efficiency, WinDusky makes a luminance calculation for any window only ONCE when it first sees the window in foreground
# Beyond that or after the user hotkey-toggles any auto-overlay off, the state is remembered and used for that sessions (unless cleared)
# The lack of this setting, or this being set to 0.0 means luminance based auto-overlay is to be disabled
# The default value is 0.7
# Note: Using this mechanism is recommended, and if so, the other rules can be commented out, else can uncomment the other rules
auto_overlay_luminance__threshold = 0.7


# Typically WinDusky uses the PrintWindow method to have request target app to draw its own pixels for us to calculate average luminance on
# An alternate method is to directly capture the screen pixels at the window's position (via BitBlt) to calculate luminance.
# The screen capture method is actually faster, but is more likely to face issues from capturing windows before they are ready, or are obscured etc
# One can try both methods to see if one works better for the applications they use, or if they want the slight speed-up of this 'alternate' method
# Note that if using the alternate method, you'll prob want a different or expanded set of exe-exclusions than for the default method
auto_overlay_luminance__use_alternate_method = false


# Windows for some apps with native dark-mode can initially come up with white background before the app paints them dark
# Specifying a delay here can help avoid some of those, at the cost of making overlays slower for all newly created windows
# The suggested value for this, if using alternate method, is 100 (in milliseconds), else a value of 0 can still be adequate
# (In addition, can simply add any such problematic exes to the exe exclusion list instead)
auto_overlay_luminance__delay_ms = 0


# Comma separated list of exes to exclude from luminance based auto-overlay application
# For instance, windows of browsers can be expected to change based on content, so one time hwnd luminance based rules might not be appropriate
auto_overlay_luminance__exclusion_exes = [
	"chrome.exe", "firefox.exe", "msedge.exe",
]


# List of exes for which WinDusky should automatically try to apply color effect as specified
# If not color effect is specified, the default color effect will be applied
# Each entry must have the 'exe' field, and can optionally specify 'effect'
# The default here, if not using luminance mothod, is to have : "msinfo32.exe", "regedit.exe", "mmc.exe",
auto_overlay_exes = [
#    { exe = "mmc.exe" },
#    { exe = "regedit.exe" },
#    { exe = "msinfo32.exe" },
#    { exe = "AutoHotkeyUX.exe",  effect = "Simple Inversion" },
]


# List of Window-classes for which WinDusky should automatically try to apply color effect as specified
# If no color effect is specified, the default color effect will be applied
# each entry must have the 'class_name' field, and can optionally specify 'effect', and a list of exe to exclude in 'exe_exclusions'
# Default (if not using luminance based auto-overlay) is to have only "#32770" which is the window class for all windows dialog popups
auto_overlay_window_classes = [
#    {
#        class_name = "#32770",
#        effect = "default",
#        exclusion_exes = ["notepad++.exe", "SystemInformer.exe"]
#    },
]





# --- Color Effects Configuration ---

# List of effect names defining the order for cycling (using Alt+Win+Period/Comma)
# Names must match the keys defined in the [color_effects] table below.
# Users can reorder, add, or remove names from this list (as long as they exist in [effects] table).
# Credit for many of these: https://github.com/mlaily/NegativeScreen
effects_cycle_order = [

    "Simple Inversion",
    "Smart Inversion V1",
    "Smart Inversion V2",
    "Smart Inversion V3",
    "Smart Inversion V4",
    "Smart Inversion V5",

    "Negative Sepia",
    "Negative Cyan",
    "Negative Green",
    "Negative Red",
    "Negative Yellow",
    "Negative Gold",
    "Negative Grayscale",
    "Negative Black and White",

    "Cyan",
    "Green",
    "Red",
    "Yellow",
    "Gold",
    "Grayscale",
    "Black and White",

    "Identity",

    ## --- Color Blindness Simulations ---
    #"Color Blindness Simulation: Protanopia (Red-Green Color Blindness)",
    #"Color Blindness Simulation: Protanomaly (red-weak)",
    #"Color Blindness Simulation: Deuteranopia (green-blind)",
    #"Color Blindness Simulation: Deuteranomaly (green-weak)",
    #"Color Blindness Simulation: Tritanopia (Blue-Yellow Color Blindness - rare)",
    #"Color Blindness Simulation: Tritanomaly (blue-yellow weak)",
    #"Color Blindness Simulation: Achromatopsia (Total color blindness)",
    #"Color Blindness Simulation: Achromatomaly (Total color weakness)",

]


# The default color-effect to use (from those defined in the table) if none is specified
# The suggested default is "Smart Inversion V3"
# The default must be an entry also in the cycle_order list
# If this is not specified, and/or does not match effects in the list, the first effect in the cycle list will be used
# Further, if the cycle list itself is empty or unspecified, a Simple Inversion matrix will be used as default
effects_default = "Smart Inversion V3"



# Definition of color effect matrices.
# Each effect has a name and a transform matrix (5x5, row-major, 25 float values).
# Users can add their own custom effects here. Ensure the name is unique and the
# transform array has exactly 25 floating-point numbers.

[[effects]]
effect = "Identity"
transform =  [
    1.0,  0.0,  0.0,  0.0,  0.0,
    0.0,  1.0,  0.0,  0.0,  0.0,
    0.0,  0.0,  1.0,  0.0,  0.0,
    0.0,  0.0,  0.0,  1.0,  0.0,
    0.0,  0.0,  0.0,  0.0,  1.0,
]

[[effects]]
effect = "Simple Inversion"
transform =  [
    -1.0,  0.0,  0.0,  0.0,  0.0,
     0.0, -1.0,  0.0,  0.0,  0.0,
     0.0,  0.0, -1.0,  0.0,  0.0,
     0.0,  0.0,  0.0,  1.0,  0.0,
     1.0,  1.0,  1.0,  0.0,  1.0,
]

[[effects]]
effect = "Smart Inversion V1"
transform =  [
     0.33,  -0.66,  -0.66,   0.0,  0.0,
    -0.66,   0.33,  -0.66,   0.0,  0.0,
    -0.66,  -0.66,   0.33,   0.0,  0.0,
      0.0,    0.0,    0.0,   1.0,  0.0,
      1.0,    1.0,    1.0,   0.0,  1.0,
]

[[effects]]
effect = "Smart Inversion V2"
transform =  [
     1.0,  -1.0,  -1.0,  0.0,  0.0,
    -1.0,   1.0,  -1.0,  0.0,  0.0,
    -1.0,  -1.0,   1.0,  0.0,  0.0,
     0.0,   0.0,   0.0,  1.0,  0.0,
     1.0,   1.0,   1.0,  0.0,  1.0,
]

[[effects]]
effect = "Smart Inversion V3"
transform =  [
     0.39,  -0.62,  -0.62,  0.0,  0.0,
    -1.21,  -0.22,  -1.22,  0.0,  0.0,
    -0.16,  -0.16,   0.84,  0.0,  0.0,
      0.0,    0.0,    0.0,  1.0,  0.0,
      1.0,    1.0,    1.0,  0.0,  1.0,
]

[[effects]]
effect = "Smart Inversion V4"
transform =  [
     1.089,  -0.932,  -0.932,  0.0,  0.0,
    -1.817,   0.168,  -1.841,  0.0,  0.0,
    -0.244,  -0.247,   1.762,  0.0,  0.0,
       0.0,     0.0,     0.0,  1.0,  0.0,
       1.0,     1.0,     1.0,  0.0,  1.0,
]

[[effects]]
effect = "Smart Inversion V5"
transform =  [
     0.50,  -0.78,  -0.78,  0.0,  0.0,
    -0.56,   0.72,  -0.56,  0.0,  0.0,
    -0.94,  -0.94,   0.34,  0.0,  0.0,
      0.0,    0.0,    0.0,  1.0,  0.0,
      1.0,    1.0,    1.0,  0.0,  1.0,
]

[[effects]]
effect = "Negative Sepia"
transform =  [
    -0.393,  -0.349,  -0.272,  0.0,  0.0,
    -0.769,  -0.686,  -0.534,  0.0,  0.0,
    -0.189,  -0.168,  -0.131,  0.0,  0.0,
       0.0,     0.0,     0.0,  1.0,  0.0,
     1.351,   1.203,   0.937,  0.0,  1.0,
]

[[effects]]
effect = "Cyan"
transform =  [
    0.0,  0.3,  0.3,  0.0,  0.0,
    0.0,  0.6,  0.6,  0.0,  0.0,
    0.0,  0.1,  0.1,  0.0,  0.0,
    0.0,  0.0,  0.0,  1.0,  0.0,
    0.0,  0.0,  0.0,  0.0,  1.0,
]

[[effects]]
effect = "Negative Cyan"
transform =  [
    0.0,  -0.3,  -0.3,  0.0,  0.0,
    0.0,  -0.6,  -0.6,  0.0,  0.0,
    0.0,  -0.1,  -0.1,  0.0,  0.0,
    0.0,   0.0,   0.0,  1.0,  0.0,
    0.0,   1.0,   1.0,  0.0,  1.0,
]

[[effects]]
effect = "Yellow"
transform =  [
    0.3,  0.3,  0.0,  0.0,  0.0,
    0.6,  0.6,  0.0,  0.0,  0.0,
    0.1,  0.1,  0.0,  0.0,  0.0,
    0.0,  0.0,  0.0,  1.0,  0.0,
    0.0,  0.0,  0.0,  0.0,  1.0,
]

[[effects]]
effect = "Negative Yellow"
transform =  [
    -0.3,  -0.3,  0.0,  0.0,  0.0,
    -0.6,  -0.6,  0.0,  0.0,  0.0,
    -0.1,  -0.1,  0.0,  0.0,  0.0,
     0.0,   0.0,  0.0,  1.0,  0.0,
     1.0,   1.0,  0.0,  0.0,  1.0,
]

[[effects]]
effect = "Gold"
transform =  [
    0.40,  0.30,  0.10,  0.0,  0.0,
    0.40,  0.30,  0.10,  0.0,  0.0,
    0.20,  0.15,  0.05,  0.0,  0.0,
     0.0,   0.0,   0.0,  1.0,  0.0,
     0.0,   0.0,   0.0,  0.0,  1.0,
]

[[effects]]
effect = "Negative Gold"
transform =  [
    -0.40,  -0.30,  -0.10,  0.0,  0.0,
    -0.40,  -0.30,  -0.10,  0.0,  0.0,
    -0.20,  -0.15,  -0.05,  0.0,  0.0,
      0.0,    0.0,    0.0,  1.0,  0.0,
     1.00,   0.85,   0.20,  0.0,  1.0,
]

[[effects]]
effect = "Green"
transform =  [
    0.0,  0.3,  0.0,  0.0,  0.0,
    0.0,  0.6,  0.0,  0.0,  0.0,
    0.0,  0.1,  0.0,  0.0,  0.0,
    0.0,  0.0,  0.0,  1.0,  0.0,
    0.0,  0.0,  0.0,  0.0,  1.0,
]

[[effects]]
effect = "Negative Green"
transform =  [
    0.0,  -0.3,  0.0,  0.0,  0.0,
    0.0,  -0.6,  0.0,  0.0,  0.0,
    0.0,  -0.1,  0.0,  0.0,  0.0,
    0.0,   0.0,  0.0,  1.0,  0.0,
    0.0,   1.0,  0.0,  0.0,  1.0,
]

[[effects]]
effect = "Red"
transform =  [
    0.3,  0.0,  0.0,  0.0,  0.0,
    0.6,  0.0,  0.0,  0.0,  0.0,
    0.1,  0.0,  0.0,  0.0,  0.0,
    0.0,  0.0,  0.0,  1.0,  0.0,
    0.0,  0.0,  0.0,  0.0,  1.0,
]

[[effects]]
effect = "Negative Red"
transform =  [
    -0.3,  0.0,  0.0,  0.0,  0.0,
    -0.6,  0.0,  0.0,  0.0,  0.0,
    -0.1,  0.0,  0.0,  0.0,  0.0,
     0.0,  0.0,  0.0,  1.0,  0.0,
     1.0,  0.0,  0.0,  0.0,  1.0,
]

[[effects]]
effect = "Grayscale"
transform =  [
    0.3,  0.3,  0.3,  0.0,  0.0,
    0.6,  0.6,  0.6,  0.0,  0.0,
    0.1,  0.1,  0.1,  0.0,  0.0,
    0.0,  0.0,  0.0,  1.0,  0.0,
    0.0,  0.0,  0.0,  0.0,  1.0,
]

[[effects]]
effect = "Negative Grayscale"
transform =  [
    -0.3,  -0.3,  -0.3,  0.0,  0.0,
    -0.6,  -0.6,  -0.6,  0.0,  0.0,
    -0.1,  -0.1,  -0.1,  0.0,  0.0,
     0.0,   0.0,   0.0,  1.0,  0.0,
     1.0,   1.0,   1.0,  0.0,  1.0,
]

[[effects]]
effect = "Black and White"
transform =  [
    127.0,    127.0,   127.0,  0.0,  0.0,
    127.0,    127.0,   127.0,  0.0,  0.0,
    127.0,    127.0,   127.0,  0.0,  0.0,
      0.0,      0.0,     0.0,  1.0,  0.0,
    -180.0,  -180.0,  -180.0,  0.0,  1.0,
]

[[effects]]
effect = "Negative Black and White"
transform =  [
    -127.0,  -127.0,  -127.0,  0.0,  0.0,
    -127.0,  -127.0,  -127.0,  0.0,  0.0,
    -127.0,  -127.0,  -127.0,  0.0,  0.0,
       0.0,     0.0,     0.0,  1.0,  0.0,
     180.0,   180.0,   180.0,  0.0,  1.0,
]



# Some more effects not typically intended for inclusion in cycle order, but here for reference:

# Color Blindness Simulation matrices
# Source: http://web.archive.org/web/20081014161121/http://www.colorjack.com/labs/colormatrix/

# http://www.color-blindness.com/protanopia-red-green-color-blindness/
# Red-Green Color Blindness   - Male Population: 1.01%, Female 0.02
[[effects]]
effect = "Color Blindness Simulation: Protanopia (Red-Green Color Blindness)"
transform = [
    0.567,  0.558,  0.000,  0.0,  0.0,
    0.433,  0.442,  0.242,  0.0,  0.0,
    0.000,  0.000,  0.758,  0.0,  0.0,
    0.000,  0.000,  0.000,  1.0,  0.0,
    0.000,  0.000,  0.000,  0.0,  1.0,
]


# http://www.color-blindness.com/protanopia-red-green-color-blindness/
# Protanomaly (red-weak)  - Male Population: 1.08%, 0.03%
[[effects]]
effect = "Color Blindness Simulation: Protanomaly (red-weak)"
transform = [
    0.817,  0.333,  0.000,  0.0,  0.0,
    0.183,  0.667,  0.125,  0.0,  0.0,
    0.000,  0.000,  0.875,  0.0,  0.0,
    0.000,  0.000,  0.000,  1.0,  0.0,
    0.000,  0.000,  0.000,  0.0,  1.0,
]


# http://www.color-blindness.com/deuteranopia-red-green-color-blindness/
# http://www.colour-blindness.com/general/prevalence/
# Deuteranopia (also called green-blind) - Male Population: 1%, Female Population: 0.1%
[[effects]]
effect = "Color Blindness Simulation: Deuteranopia (green-blind)"
transform = [
    0.625,  0.700,  0.000,  0.0,  0.0,
    0.375,  0.300,  0.300,  0.0,  0.0,
    0.000,  0.000,  0.700,  0.0,  0.0,
    0.000,  0.000,  0.000,  1.0,  0.0,
    0.000,  0.000,  0.000,  0.0,  1.0,
]


# http://www.colour-blindness.com/general/prevalence/
# Deuteranomaly (green-weak) - Male Population: 5%, Female Population: 0.35%
[[effects]]
effect = "Color Blindness Simulation: Deuteranomaly (green-weak)"
transform = [
    0.800,  0.258,  0.000,  0.0,  0.0,
    0.200,  0.742,  0.142,  0.0,  0.0,
    0.000,  0.000,  0.858,  0.0,  0.0,
    0.000,  0.000,  0.000,  1.0,  0.0,
    0.000,  0.000,  0.000,  0.0,  1.0,
]


# http://www.color-blindness.com/tritanopia-blue-yellow-color-blindness/
# http://www.colour-blindness.com/general/prevalence/
# Tritanopia  Blue-Yellow Color Blindness - rare. Some sources estimate 0.008%
[[effects]]
effect = "Color Blindness Simulation: Tritanopia (Blue-Yellow Color Blindness - rare)"
transform = [
    0.950,  0.000,  0.000,  0.0,  0.0,
    0.050,  0.433,  0.475,  0.0,  0.0,
    0.000,  0.567,  0.525,  0.0,  0.0,
    0.000,  0.000,  0.000,  1.0,  0.0,
    0.000,  0.000,  0.000,  0.0,  1.0,
]


# http://www.color-blindness.com/tritanopia-blue-yellow-color-blindness/
# http://www.colour-blindness.com/general/prevalence/
# Tritanomaly (blue-yellow weak) - Male 0.01%, Female 0.01%
[[effects]]
effect = "Color Blindness Simulation: Tritanomaly (blue-yellow weak)"
transform = [
    0.967,  0.000,  0.000,  0.0,  0.0,
    0.033,  0.733,  0.183,  0.0,  0.0,
    0.000,  0.267,  0.817,  0.0,  0.0,
    0.000,  0.000,  0.000,  1.0,  0.0,
    0.000,  0.000,  0.000,  0.0,  1.0,
]


# http://www.color-blindness.com/2007/07/20/monochromacy-complete-color-blindness/
# Total color blindness - Occurrences are estimated to be between 1 : 30000 and 1 : 50000.
[[effects]]
effect = "Color Blindness Simulation: Achromatopsia (Total color blindness)"
transform = [
    0.299,  0.299,  0.299,  0.0,  0.0,
    0.587,  0.587,  0.587,  0.0,  0.0,
    0.114,  0.114,  0.114,  0.0,  0.0,
    0.000,  0.000,  0.000,  1.0,  0.0,
    0.000,  0.000,  0.000,  0.0,  1.0,
]


# http://www.color-blindness.com/2007/07/20/monochromacy-complete-color-blindness/
# All color-weak - Different sources vary between 1 in 33000 to 100000 (0.001%).
[[effects]]
effect = "Color Blindness Simulation: Achromatomaly (Total color weakness)"
transform = [
    0.618,  0.163,  0.163,  0.0,  0.0,
    0.320,  0.775,  0.320,  0.0,  0.0,
    0.062,  0.062,  0.516,  0.0,  0.0,
    0.000,  0.000,  0.000,  1.0,  0.0,
    0.000,  0.000,  0.000,  0.0,  1.0,
]
