

## Config settings file for WinDusky appliation .. uses toml format
# (Note that in toml format, root keys must be listed before any tables with square-brackets are started)
#
# The application will look for this file (WinDusky.conf.toml) in the same directory from which it is running (if the location is writeable)
# If that location is not writeable, the config file will pick  ~/AppData/Local/WinDusky/ as conf file location
# Upon startup, if the conf file is not present in the location selected as above, a default conf file will be created in that location
# Configurations modified at run time will be written back to this file
# Most changes to this file (unless specified in the config) will be picked up by the application upon reload or restart



# WinDusky conf version string .. this is used to check compatibility and print warnings/errors
# Upon upgrading the application, and updating any user configs here as desired, can update this version string to remove warning printouts
dusky_conf_version = 0.13



# Hotkey to toggle WinDusky on currectly active window, specified as a string ..
# The default is "Alt+Win+I" .. I for 'invert' .. specified as { key = "I", modifiers = ["Alt", "Win"] }
# Hotkey specification strings mostly map to tauri hotkey specs .. they are summarized below :
#   Alt, Shift, Ctrl, Win, A-Z, 0-9, F1-F24, Comma, Period, Plus, Minus, etc,
#   ArrowUp, ArrowDown, ArrowLeft, ArrowRight, Home, End, PageUp, PageDown,
#   Space, Enter, Backspace, Delete, Insert, Tab, Escape
#
# Note: Updates to this config are ONLY picked up upon restarting (not just reloading) the application
dusky_toggle_hotkey = { key = "I", modifiers = ["Alt", "Win"] }


# Hotkeys to cycle through (next and previous) color-effects in the color-effects list
# The defaults are Alt+Win+Period for Next, and Alt+Win+Comma for Previous effect
dusky_next_effect_hotkey = { key = "Period", modifiers = ["Alt", "Win"] }
dusky_prev_effect_hotkey = { key = "Comma",  modifiers = ["Alt", "Win"] }



# Enable logging for debugging or reporting errors .. default is false
# When enabled, the log files with names like "switche_log.<date>.log" will be generated in the same location as the active config file
# Note: Enabling logging is ONLY picked up upon restarting (not just reloading) the application
logging_enabled = true

# Level of logging (if enabled) .. default is "INFO" .. options are "DEBUG", "INFO", "WARN", "ERROR"
logging_level = "DEBUG"




# --- Auto Overlay Configuration ---
# Note: The 'effect' field here now refers to names defined in [color_effects].
# Use "default" to apply the effect specified in 'effects_default'
# This default also gets used if notthing is specified

# List of exes for which WinDusky should automatically try to apply color effect as specified
# If not color effect is specified, the default color effect will be applied
# each entry must have the 'exe' field, and can optionally specify 'effect'
# default is to have : "msinfo32.exe", "regedit.exe", "mmc.exe",
auto_overlay_exes = [
    { exe = "mmc.exe" },
    { exe = "regedit.exe" },
    { exe = "msinfo32.exe" },
    { exe = "WinaeroTweaker.exe" },
    { exe = "autohotkeyUX.exe",  effect = "Simple Inversion" },
]


# List of Window-classes for which WinDusky should automatically try to apply color effect as specified
# If not color effect is specified, the default color effect will be applied
# each entry must have the 'class_name' field, and can optionally specify 'effect', and a list of exe to exclude in 'exe_exclusions'
# Default is to have only "#32770" which is the window class for all dialog popups that windows generates
auto_overlay_window_classes = [
    { class_name = "#32770", effect = "default", exe_exclusions = ["notepad++.exe"] },
]






# --- Color Effects Configuration ---

# List of effect names defining the order for cycling (using Alt+Win+Period/Comma)
# Names must match the keys defined in the [color_effects] table below.
# Users can reorder, add, or remove names from this list (as long as they exist in [effects] table).
effects_cycle_order = [

    "Simple Inversion",
    "Smart Inversion V1",
    "Smart Inversion V2",
    "Smart Inversion V3",
    "Smart Inversion V4",
    "Smart Inversion V5",
    "Negative Sepia",

    "Negative Cyan",
    "Negative Green",
    "Negative Red",
    "Negative Yellow",
    "Negative Gold",
    "Negative Grayscale",
    "Negative Black and White",

    "Cyan",
    "Green",
    "Red",
    "Yellow",
    "Gold",
    "Grayscale",
    "Black and White",

    "Identity",

]


# The default color-effect to use (from those defined in the table) if none is specified
# The suggested default is "Smart Inversion V3"
# The default must be an entry also in the cycle_order list
# If this is not specified, and/or does not match effects in the list, the first effect in the cycle list will be used
# Further, if the cycle list itself is empty or unspecified, a Simple Inversion matrix will be used as default
effects_default = "Smart Inversion V3"



# Definition of color effect matrices.
# Each effect has a name and a transform matrix (5x5, row-major, 25 float values).
# Users can add their own custom effects here. Ensure the name is unique and the
# transform array has exactly 25 floating-point numbers.

[[effects]]
effect = "Identity"
transform =  [
    1.0,  0.0,  0.0,  0.0,  0.0,
    0.0,  1.0,  0.0,  0.0,  0.0,
    0.0,  0.0,  1.0,  0.0,  0.0,
    0.0,  0.0,  0.0,  1.0,  0.0,
    0.0,  0.0,  0.0,  0.0,  1.0,
]

[[effects]]
effect = "Simple Inversion"
transform =  [
    -1.0,  0.0,  0.0,  0.0,  0.0,
     0.0, -1.0,  0.0,  0.0,  0.0,
     0.0,  0.0, -1.0,  0.0,  0.0,
     0.0,  0.0,  0.0,  1.0,  0.0,
     1.0,  1.0,  1.0,  0.0,  1.0,
]

[[effects]]
effect = "Smart Inversion V1"
transform =  [
     0.33,  -0.66,  -0.66,   0.0,  0.0,
    -0.66,   0.33,  -0.66,   0.0,  0.0,
    -0.66,  -0.66,   0.33,   0.0,  0.0,
      0.0,    0.0,    0.0,   1.0,  0.0,
      1.0,    1.0,    1.0,   0.0,  1.0,
]

[[effects]]
effect = "Smart Inversion V2"
transform =  [
     1.0,  -1.0,  -1.0,  0.0,  0.0,
    -1.0,   1.0,  -1.0,  0.0,  0.0,
    -1.0,  -1.0,   1.0,  0.0,  0.0,
     0.0,   0.0,   0.0,  1.0,  0.0,
     1.0,   1.0,   1.0,  0.0,  1.0,
]

[[effects]]
effect = "Smart Inversion V3"
transform =  [
     0.39,  -0.62,  -0.62,  0.0,  0.0,
    -1.21,  -0.22,  -1.22,  0.0,  0.0,
    -0.16,  -0.16,   0.84,  0.0,  0.0,
      0.0,    0.0,    0.0,  1.0,  0.0,
      1.0,    1.0,    1.0,  0.0,  1.0,
]

[[effects]]
effect = "Smart Inversion V4"
transform =  [
     1.089,  -0.932,  -0.932,  0.0,  0.0,
    -1.817,   0.168,  -1.841,  0.0,  0.0,
    -0.244,  -0.247,   1.762,  0.0,  0.0,
       0.0,     0.0,     0.0,  1.0,  0.0,
       1.0,     1.0,     1.0,  0.0,  1.0,
]

[[effects]]
effect = "Smart Inversion V5"
transform =  [
     0.50,  -0.78,  -0.78,  0.0,  0.0,
    -0.56,   0.72,  -0.56,  0.0,  0.0,
    -0.94,  -0.94,   0.34,  0.0,  0.0,
      0.0,    0.0,    0.0,  1.0,  0.0,
      1.0,    1.0,    1.0,  0.0,  1.0,
]

[[effects]]
effect = "Negative Sepia"
transform =  [
    -0.393,  -0.349,  -0.272,  0.0,  0.0,
    -0.769,  -0.686,  -0.534,  0.0,  0.0,
    -0.189,  -0.168,  -0.131,  0.0,  0.0,
       0.0,     0.0,     0.0,  1.0,  0.0,
     1.351,   1.203,   0.937,  0.0,  1.0,
]

[[effects]]
effect = "Cyan"
transform =  [
    0.0,  0.3,  0.3,  0.0,  0.0,
    0.0,  0.6,  0.6,  0.0,  0.0,
    0.0,  0.1,  0.1,  0.0,  0.0,
    0.0,  0.0,  0.0,  1.0,  0.0,
    0.0,  0.0,  0.0,  0.0,  1.0,
]

[[effects]]
effect = "Negative Cyan"
transform =  [
    0.0,  -0.3,  -0.3,  0.0,  0.0,
    0.0,  -0.6,  -0.6,  0.0,  0.0,
    0.0,  -0.1,  -0.1,  0.0,  0.0,
    0.0,   0.0,   0.0,  1.0,  0.0,
    0.0,   1.0,   1.0,  0.0,  1.0,
]

[[effects]]
effect = "Yellow"
transform =  [
    0.3,  0.3,  0.0,  0.0,  0.0,
    0.6,  0.6,  0.0,  0.0,  0.0,
    0.1,  0.1,  0.0,  0.0,  0.0,
    0.0,  0.0,  0.0,  1.0,  0.0,
    0.0,  0.0,  0.0,  0.0,  1.0,
]

[[effects]]
effect = "Negative Yellow"
transform =  [
    -0.3,  -0.3,  0.0,  0.0,  0.0,
    -0.6,  -0.6,  0.0,  0.0,  0.0,
    -0.1,  -0.1,  0.0,  0.0,  0.0,
     0.0,   0.0,  0.0,  1.0,  0.0,
     1.0,   1.0,  0.0,  0.0,  1.0,
]

[[effects]]
effect = "Gold"
transform =  [
    0.40,  0.30,  0.10,  0.0,  0.0,
    0.40,  0.30,  0.10,  0.0,  0.0,
    0.20,  0.15,  0.05,  0.0,  0.0,
     0.0,   0.0,   0.0,  1.0,  0.0,
     0.0,   0.0,   0.0,  0.0,  1.0,
]

[[effects]]
effect = "Negative Gold"
transform =  [
    -0.40,  -0.30,  -0.10,  0.0,  0.0,
    -0.40,  -0.30,  -0.10,  0.0,  0.0,
    -0.20,  -0.15,  -0.05,  0.0,  0.0,
      0.0,    0.0,    0.0,  1.0,  0.0,
     1.00,   0.85,   0.20,  0.0,  1.0,
]

[[effects]]
effect = "Green"
transform =  [
    0.0,  0.3,  0.0,  0.0,  0.0,
    0.0,  0.6,  0.0,  0.0,  0.0,
    0.0,  0.1,  0.0,  0.0,  0.0,
    0.0,  0.0,  0.0,  1.0,  0.0,
    0.0,  0.0,  0.0,  0.0,  1.0,
]

[[effects]]
effect = "Negative Green"
transform =  [
    0.0,  -0.3,  0.0,  0.0,  0.0,
    0.0,  -0.6,  0.0,  0.0,  0.0,
    0.0,  -0.1,  0.0,  0.0,  0.0,
    0.0,   0.0,  0.0,  1.0,  0.0,
    0.0,   1.0,  0.0,  0.0,  1.0,
]

[[effects]]
effect = "Red"
transform =  [
    0.3,  0.0,  0.0,  0.0,  0.0,
    0.6,  0.0,  0.0,  0.0,  0.0,
    0.1,  0.0,  0.0,  0.0,  0.0,
    0.0,  0.0,  0.0,  1.0,  0.0,
    0.0,  0.0,  0.0,  0.0,  1.0,
]

[[effects]]
effect = "Negative Red"
transform =  [
    -0.3,  0.0,  0.0,  0.0,  0.0,
    -0.6,  0.0,  0.0,  0.0,  0.0,
    -0.1,  0.0,  0.0,  0.0,  0.0,
     0.0,  0.0,  0.0,  1.0,  0.0,
     1.0,  0.0,  0.0,  0.0,  1.0,
]

[[effects]]
effect = "Grayscale"
transform =  [
    0.3,  0.3,  0.3,  0.0,  0.0,
    0.6,  0.6,  0.6,  0.0,  0.0,
    0.1,  0.1,  0.1,  0.0,  0.0,
    0.0,  0.0,  0.0,  1.0,  0.0,
    0.0,  0.0,  0.0,  0.0,  1.0,
]

[[effects]]
effect = "Negative Grayscale"
transform =  [
    -0.3,  -0.3,  -0.3,  0.0,  0.0,
    -0.6,  -0.6,  -0.6,  0.0,  0.0,
    -0.1,  -0.1,  -0.1,  0.0,  0.0,
     0.0,   0.0,   0.0,  1.0,  0.0,
     1.0,   1.0,   1.0,  0.0,  1.0,
]

[[effects]]
effect = "Black and White"
transform =  [
    127.0,    127.0,   127.0,  0.0,  0.0,
    127.0,    127.0,   127.0,  0.0,  0.0,
    127.0,    127.0,   127.0,  0.0,  0.0,
      0.0,      0.0,     0.0,  1.0,  0.0,
    -180.0,  -180.0,  -180.0,  0.0,  1.0,
]

[[effects]]
effect = "Negative Black and White"
transform =  [
    -127.0,  -127.0,  -127.0,  0.0,  0.0,
    -127.0,  -127.0,  -127.0,  0.0,  0.0,
    -127.0,  -127.0,  -127.0,  0.0,  0.0,
       0.0,     0.0,     0.0,  1.0,  0.0,
     180.0,   180.0,   180.0,  0.0,  1.0,
]

